# Generated by Django 4.2.16 on 2024-10-05 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RFIDCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_id", models.CharField(max_length=100, unique=True)),
                ("owner", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("T", "Temperature"),
                            ("H", "Outside Humidity"),
                            ("P", "Outside Pressure"),
                            ("G", "Outside Gas"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.FloatField()),
                ("date", models.DateTimeField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="measurements.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CurrentMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("T", "Temperature"),
                            ("H", "Outside Humidity"),
                            ("P", "Outside Pressure"),
                            ("G", "Outside Gas"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.FloatField()),
                ("date", models.DateTimeField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="measurements.room",
                    ),
                ),
            ],
        ),
    ]
